name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.101'

      - name: run test
        run: dotnet test

      - name: Publish
        run: dotnet publish ./src/Marion.Dalifard.FeatureMatching.Console/Marion.Dalifard.FeatureMatching.Console.csproj --self-contained true --output ./win-x64/featurematching.exe -c Release -r win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Publis FaceDetection Console
          path: ./win-x64/featurematching.exe