name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.101'

      - name: Build and test
        run: |
          dotnet build --configuration Release
          dotnet test

      - name: Publish
        run: |
          dotnet publish -c Release -r win10-x64 --self-contained src/Marion.Dalifard.FeatureMatching.Console/Marion.Dalifard.FeatureMatching.Console.csproj

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: published-app
          path: ./bin/Release/netcoreapp3.1/win10-x64/publish